version: '3.8'
services:
  gateway:
    build: ./gateway
#    image: amazoncorretto:11-alpine-jdk
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - db
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
#    image: amazoncorretto:11-alpine-jdk
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
#      TZ: "Europe/Moscow"
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
#      DB_HOST: db
#      DB_PORT: 5432
#      DB_NAME: shareit
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres


  db:
    image: postgres:14.5-alpine
    container_name: postgres
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
