CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );

create table IF NOT EXISTS REQUESTS
(
    ID              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DESCRIPTION     VARCHAR(512),
    requestor_id BIGINT,
    created TIMESTAMP without time zone,
    constraint REQUESTS_PK primary key (ID),
    constraint REQUESTS_USERS_ID_FK foreign key (REQUESTOR_ID) references USERS (id)

);


create table IF NOT EXISTS ITEMS
(
    ID           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NAME         VARCHAR(255),
    DESCRIPTION  VARCHAR(512),
    IS_AVAILABLE BOOLEAN,
    owner_id BIGINT,
    REQUEST_ID   BIGINT,
    constraint ITEMS_PK primary key (ID),
    constraint ITEMS_USERS_ID_FK foreign key (owner_id) references USERS (id),
    constraint ITEMS_REQUESTS_ID_FK foreign key (REQUEST_ID) references REQUESTS (ID)
);

create table IF NOT EXISTS BOOKINGS
(
    ID            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP without time zone,
    END_DATE      TIMESTAMP without time zone,
    ITEM_ID       BIGINT,
    BOOKER_ID     BIGINT,
    STATUS        VARCHAR(512),
    constraint BOOKINGS_PK primary key (ID),
    constraint BOOKINGS_ITEMS_ID_FK foreign key (ITEM_ID) references ITEMS (ID),
    constraint BOOKINGS_USERS_ID_FK foreign key (BOOKER_ID) references USERS (id)
);



create table IF NOT EXISTS COMMENTS
(
    ID        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    TEXT      VARCHAR(512),
    ITEM_ID   BIGINT,
    AUTHOR_ID BIGINT,
    created TIMESTAMP without time zone,
    constraint COMMENTS_PK primary key (ID),
    constraint COMMENTS_ITEMS_ID_FK foreign key (ITEM_ID) references ITEMS,
    constraint COMMENTS_USERS_ID_FK foreign key (AUTHOR_ID) references USERS
);
